### PR TITLE
Added obw's cog

### PR DESCRIPTION
**Pull request by hedgehog1029**
this is version 1 of my cog

👏 👏 👏

### CODE REVIEW

**Comment by EJH2** [comment]
Tfw the poorly rendered ASCII logo is as long as the rest of your code :^)

**Comment by hedgehog1029** [comment]
at least it's bigger than luna's cog

**Comment by EJH2** [comment]
O shit ur right

**Comment by ReinaSakuraba** [comment]
Not enough typing abuse

**Pull request merged**
