### PR TITLE
Improve everything 

### PR DESCRIPTION
**Pull request by ReinaSakuraba**

### CODE REVIEW

**Comment by Ikusaba-san** [comment]
No.

**Comment by ghost** [comment]
No

**Comment by ReinaSakuraba** [comment]
No

**Comment by EvieePy** [comment]
Please merge. Good fix.

**Comment by NCPlayz** [comment]
^^^^^

**Comment by Ikusaba-san** [comment]
:thinking:

Still no.

**Comment by NCPlayz** [comment]
I mean you can revert it...

**Comment by ReinaSakuraba** [comment]
Trying to sleep and notifications keep waking me up

**Pull request closed without merging**
